#  
# Project's build CI
#

name: build


on:
    push:
        branches: [ particles ]

    pull_request:
        branches: [ particles ]


permissions:
    contents:   read
    pages:      write


jobs:
    build:
        runs-on: windows-latest

        steps:
            # clones the rep. into the runner s.t. the workflow can access the code.
            - uses:     actions/checkout@v4

            - name:     Cache EMSDK
              uses:     actions/cache@v4
              with:
                    path: ${{ env.USERPROFILE }}\dev\downloads\emsdk
                    key: emsdk-${{ runner.os }}-latest

            - name:     Install EMSDK
              shell:    pwsh
              run: |    
                    $emsdk = "$env:USERPROFILE\dev\downloads\emsdk"
                            
                    if (!(Test-Path emsdk)) {
                        git clone https://github.com/emscripten-core/emsdk.git $emsdk
                    }
                  
                    cd $emsdk
                  
                    .\emsdk install latest
                    .\emsdk activate latest

            - name:     Configure
              run:      src/hps/.configure.ps1

            - name:     Build
              run:      src/hps/.build.ps1

            - name:     Copy to Pages
              run:      src/hps/.copy.ps1
